config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  resources :contacts, only: [:show, :new, :create] do 
    member do
      get :confirm_email
      get :renew_email
      get :optout_email
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord

    validates_presence_of :firstname, :lastname, :phone_number, :email 
    validates_length_of :firstname, :lastname, minimum: 2, maximum: 40
    validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
    validates_uniqueness_of :email, :phone_number

    before_create :confirmation_token


    def confirmed!
        self.email_confirmation = true
        save!
        
    end

    def optout!
        self.email_confirmation = false
        self.renewed_on = nil
        save!
        
    end

    def validated_on!
        self.validated_on = DateTime.now
        save!
    end
    
    
    def renew!
        self.renewed_on = DateTime.now
        save!
    end
   
    private
   
   def confirmation_token
        if self.confirm_token.blank?
            self.confirm_token = SecureRandom.urlsafe_base64.to_s
        end
   end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
   
    def show
        find_contact
        if @contact.validated_on.nil? && @contact.email_confirmation == false 
            @text = "Tu n'as pas encore de position dans la liste! verifie tes emails 🙂"
            @position = "Inscritpion non confirmée"
        elsif @contact.validated_on != nil && @contact.email_confirmation == false
            @text = "Ton inscription sur la liste est bien annulée. N'hésites pas à revenir."
            @position = "😢"
        elsif @contact.email_confirmation == true && @contact.renewed_on !=nil
            @prospects = Contact.where("email_confirmation = true")
            @list = @prospects.sort_by{ |contact| contact[:validated_on]}
            @text = "Ta position dans la liste d'attente est bien renouvellée à la place suivante:"
            @position = @list.index{ |contact| contact[:email] == @contact.email} + 1
        else
            @prospects = Contact.where("email_confirmation = true")
            @list = @prospects.sort_by{ |contact| contact[:validated_on]}
            @text = "Ta position dans la liste d'attente est la suivante:"
            @position = @list.index{ |contact| contact[:email] == @contact.email} + 1
        end
    end
    
    
    def new
        @contact = Contact.new
    end

    def create
        @contact = Contact.new(contact_params)
        if @contact.save
          ContactMailer.welcome(@contact).deliver_later
          flash[:notice] = "contact successfully created"
          redirect_to root_path
          
        else
          flash[:notice] = "Something went wrong"
          render 'new'
          
        end
    end

    def confirm_email
        @contact = Contact.find_by_confirm_token(params[:id])
        if @contact
            @contact.confirmed!
            @contact.validated_on!
            ContactMailer.renew(@contact).deliver_later(wait_until: 15.days.from_now)
            Check20Job.set(wait_until: 20.days.from_now).perform_later(@contact.id)
            flash[:notice] = "Added on the wait list !"
            redirect_to contact_path(@contact)
            
        else
            flash[:notice] = "something went wrong"
            redirect_to root_path
            
        end
    end

    def renew_email
        @contact = Contact.find_by_confirm_token(params[:id])
        if @contact
            @contact.renew!
            ContactMailer.renew(@contact).deliver_later(wait_until: 15.days.from_now)
            Check20Job.set(wait_until: 20.days.from_now).perform_later(@contact.id)
            flash[:notice] = "Position confirmed!"
            redirect_to contact_path(@contact)
            
        else
            flash[:notice] = "something went wrong"
            redirect_to root_path
            
        end
    end
    
    def optout_email
        @contact = Contact.find_by_confirm_token(params[:id])
        if @contact
            @contact.optout!
            flash[:notice] = "Removed from the list!"
            redirect_to contact_path(@contact)
            
        else
            flash[:notice] = "something went wrong"
            redirect_to root_path
            
        end
    end
        
    private

    def find_contact
        @contact = Contact.find(params[:id])
    end

    def contact_params
        params.require(:contact).permit(:firstname, :lastname, :email, :phone_number) 
    end

    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<div class="container">
    <%= simple_form_for @contact do |f| %>
    <%= f.input :firstname, label: "Enter your Firstname" %>
    <%= f.input :lastname, label: "Enter your Lastname" %>
    <%= f.input :phone_number, label: "Enter your phone number" %>
    <%= f.input :email, label: "Enter your email" %>
    <%= f.submit "Inscrivez moi !", class: "btn btn-primary" %>
    <% end %>
</div>

app/views/contacts/show.html.erb
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Hello <%= @contact.firstname %> 🌞</h1>
        <p class="lead text-muted"> <%= @text %></p>
        <h2 class="fw-light"> <%= @position %> </h2>
        <p>
          <%= link_to "retour à la page d'acceuil", root_path, class: "btn btn-outline-dark my-2" %>
        </p>
      </div>
    </div>
  </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WaitingList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Inscrivez-vous maintenant !</h1>
        <p class="lead text-muted"> Nos espaces résidents sont occupés pour le moment, inscrivez vous sur la liste d'attente pour votre bureau de rêve à Brest !</p>
        <p>
          <%= link_to "Inscription", new_contact_path, class: "btn btn-primary my-2" %>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-2 bg-light">
    <div class="container">

      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Bureau résident</text></svg>

            <div class="card-body">
              <p class="card-text">Votre Super bureau permanent, disponible 24/7, services premium.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">Plus d'infos</button>
                </div>
                <small class="text-muted">0 disponible</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Bureau Nomade</text></svg>

            <div class="card-body">
              <p class="card-text">Super bureau flexible, disponible 7/7 aux horaires d'ouverture.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">Plus d'infos</button>
                </div>
                <small class="text-muted">0 disponible</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="card shadow-sm">
            <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Bureau Superflex</text></svg>

            <div class="card-body">
              <p class="card-text">Venez comme vous êtes, on vous trouvera un coin.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">Plus d'infos</button>
                </div>
                <small class="text-muted">0 disponible</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</main>

app/views/shared/_flashes.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= flash[:notice] %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-coworking">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo_brest_coworking.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "HOME", root_path, class: "nav-link" %>
        </li>


      </ul>
    </div>
  </div>

</div>